import os


class Config:
    TIMETREE_EMAIL = os.getenv("TIMETREE_EMAIL")
    TIMETREE_PASSWORD = os.getenv("TIMETREE_PASSWORD")
    TIMETREE_CALENDAR_CODE = os.getenv("TIMETREE_CALENDAR_CODE")
    GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")
    GOOGLE_CALENDAR_ID_SHARED = os.getenv("GOOGLE_CALENDAR_ID_SHARED")
    GOOGLE_CALENDAR_ID_MOMOKO = os.getenv("GOOGLE_CALENDAR_ID_MOMOKO")
    GOOGLE_CALENDAR_ID_KENTA = os.getenv("GOOGLE_CALENDAR_ID_KENTA")
    GOOGLE_CALENDAR_ID_MOMOKO_WORK = os.getenv("GOOGLE_CALENDAR_ID_MOMOKO_WORK")
    GOOGLE_CALENDAR_ID_KENTA_WORK = os.getenv("GOOGLE_CALENDAR_ID_KENTA_WORK")

    @classmethod
    def validate(cls):
        required = {
            "TIMETREE_EMAIL": cls.TIMETREE_EMAIL,
            "TIMETREE_PASSWORD": cls.TIMETREE_PASSWORD,
            "TIMETREE_CALENDAR_CODE": cls.TIMETREE_CALENDAR_CODE,
            "GOOGLE_SERVICE_ACCOUNT_JSON": cls.GOOGLE_SERVICE_ACCOUNT_JSON,
            "GOOGLE_CALENDAR_ID_SHARED": cls.GOOGLE_CALENDAR_ID_SHARED,
            "GOOGLE_CALENDAR_ID_MOMOKO": cls.GOOGLE_CALENDAR_ID_MOMOKO,
            "GOOGLE_CALENDAR_ID_KENTA": cls.GOOGLE_CALENDAR_ID_KENTA,
            "GOOGLE_CALENDAR_ID_MOMOKO_WROK": cls.GOOGLE_CALENDAR_ID_MOMOKO_WORK,
            "GOOGLE_CALENDAR_ID_KENTA_WROK": cls.GOOGLE_CALENDAR_ID_KENTA_WORK,
        }
        missing = [key for key, value in required.items() if not value]
        if missing:
            raise RuntimeError("Missing environment variables: " + ", ".join(missing))
